name: readtogether_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0
  google_fonts: ^6.3.2
  file_picker: ^10.3.7
  path_provider: ^2.1.5
  webview_flutter: 4.13.0
  webview_flutter_android: ^4.10.9
  webview_flutter_wkwebview: ^3.23.2
  open_file: ^3.5.10
  url_launcher: ^6.2.2
  flutter_inappwebview: ^6.0.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/data/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"